SELECT RESTAURANTS.NOM
FROM RESTAURANTS 
WHERE VILLE IN ('Bayonne','Anglet','Biarritz');

SELECT RESTAURANTS.NOM
FROM RESTAURANTS JOIN SERVICEPLATS ON RESTAURANTS.CODE = SERVICEPLATS.CODERESTAURANTS
GROUP BY RESTAURANTS.NOM
HAVING 